### ISSUE TITLE
table bug

### ISSUE THREAD

**Issue by xiaokaike** [luojilab/radon-ui#10]
![d](https://cloud.githubusercontent.com/assets/4251499/18153327/5b8f59e8-702f-11e6-9e0f-f8d0c03dbd4d.gif)

**Comment by hilongjw** [comment]
@xiaokaike 是现在的文档演示吗？可以提供一下系统和浏览器环境，我现在没有复现这个问题

**Comment by xiaokaike** [comment]
mac safari Version 9.1.2 (11601.7.7)

**Comment by hilongjw** [comment]
已修复，取消了用click事件冒泡来切换，改用watch实现
