### ISSUE TITLE
安卓4.4 努比亚上传问题

### ISSUE THREAD

**Issue by sunday-star** [luojilab/radon-ui#12]
点击上传按钮弹出没有可执行操作的应用程序

**Comment by taomas** [comment]
额，我也想问一下这个上传组件应该怎么上传到服务器上面呢？

看代码好像是通过`input`标签上传文件然后通过`window.URL.createObjectURL`获取了一个预览路径。

但是好像不支持上传到服务器上呀？

**Comment by sunday-star** [comment]
上传到服务器是选完图片的后续动作，现在直接就没有弹出选项框，直接告诉我没有应用可以执行此操作，我尝试把:accept参数拿掉以后，神奇的好了

**Comment by hilongjw** [comment]
@sunday-star 没有在移动端做大量测试，android 4.4 不支持 accept？

**Comment by hilongjw** [comment]
@wendaosanshou 图片的上传可能会涉及更多的业务逻辑，所以就没有把上传这一步封装在内部，直接在外部监听文件选择的事件然后就可以调用自己的上传方法上传了

**Comment by sunday-star** [comment]
尝试了用原始的input.file，加了accept，点击是可以弹出选择相册进行上传的，如果你直接封装好了，就更好了

**Comment by taomas** [comment]
@hilongjw 哦，谢谢，明白了。写的很棒，代码都很优雅很简洁啊，赞！

看了你们的组件格式后，发现样式写在最上面也挺好的，哈哈。

**Comment by hilongjw** [comment]
@sunday-star 之后我会检查一下 accept 这里的兼容问题

**Comment by hilongjw** [comment]
@sunday-star 可能是 之前的accept 参数不标准导致的兼容问题，现在我提供了一个accept 接口来处理

**Comment by sunday-star** [comment]
@hilongjw 谢谢了
