### ISSUE TITLE
时间选择器，除了选择分秒的，其他的点击确定不会消失

### ISSUE THREAD

**Issue by treasureDouDou** [luojilab/radon-ui#13]

**Comment by treasureDouDou** [comment]
希望早点修复，改了源码怕同事不会弄

**Comment by hilongjw** [comment]
@qq564526299 可以描述清楚一点吗？没get到问题出在哪里

**Comment by treasureDouDou** [comment]
不是点开时间选择器会出现选择时间的框吗？这时候直接点确定，除了选择分秒的点确定，弹出框能消失，其他都不能，除非去选择月年再点击确定才会消失

**Comment by treasureDouDou** [comment]
@hilongjw  https://luojilab.github.io/radon-ui/#!/form/datepicker                   地址

**Comment by hilongjw** [comment]
@qq564526299 感谢反馈，已经修复

**Comment by treasureDouDou** [comment]
@hilongjw npm放上去了吗，放上去我更新下

**Comment by hilongjw** [comment]
@qq564526299 OK
