### ISSUE TITLE
Radio 单选框无法使用，报错，

### ISSUE THREAD

**Issue by treasureDouDou** [luojilab/radon-ui#15]
https://luojilab.github.io/radon-ui/#!/form/radio  地址

vue.common.js?1090:1019 [Vue warn]: Error when evaluating expression "{
        'checked': radio.checked,
        'disabled': radio.disabled
    }": TypeError: Cannot read property 'checked' of undefined (found in component: <rd-radio>)

[Vue warn]: Error when evaluating expression "radio.value": TypeError: Cannot read property 'value' of undefined (found in component: <rd-radio>)

**Comment by treasureDouDou** [comment]
把官网代码复制下拉就这样

**Comment by hilongjw** [comment]
@qq564526299 在data 中声明了对象吗？可以的话，贴一下当前的代码
