### ISSUE TITLE
Vue 2.0 webpack 编译时发生3个语法错误

### ISSUE THREAD

**Issue by everpointer** [luojilab/radon-ui#18]
#### 本地环境
- 相关组件版本:  vue 2.0.0-rc4 radon-ui 0.1.7 node 6.2.0
- 操作系统及其版本：OS X 10.11.5
- 浏览器及其版本: 
#### 错误内容
1. alert.vue：template syntax error Cannot use v-for on stateful component root element because it renders multiple elements
2. progressCircle.vue：template syntax error duplicate attribute: class
3. modal.vue：template syntax error - invalid expression:
                   {{{modal.rawContent}}}

**具体错误提示如下：**

ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-27!./~/vue-loader/lib/selector.js?type=template&index=0!./~/radon-ui/dist/components/common/alert.vue
template syntax error Cannot use v-for on stateful component root element because it renders multiple elements:

```
<div
    class="rd-alert"
    :class="classType(alert)"
    v-for="alert in alerts"
>
    <span
        class="rd-alert-icon"
        :class="iconClass(alert)"
    ></span>
    <div class="rd-alert-body">
        <span class="rd-alert-title">{{alert.title}}</span>
        <p v-if="alert.content" class="rd-alert-content">{{alert.content}}</p>
    </div>
</div>
```

 @ ./~/radon-ui/dist/components/common/alert.vue 7:23-139
 @ ./~/radon-ui/dist/components/index.js
 @ ./src/main.js
 @ multi main

ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-31!./~/vue-loader/lib/selector.js?type=template&index=0!./~/radon-ui/dist/components/common/progressCircle.vue
template syntax error duplicate attribute: class
 @ ./~/radon-ui/dist/components/common/progressCircle.vue 7:23-148
 @ ./~/radon-ui/dist/components/index.js
 @ ./src/main.js
 @ multi main

ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-34!./~/vue-loader/lib/selector.js?type=template&index=0!./~/radon-ui/dist/components/global/modal.vue
template syntax error - invalid expression:
                    {{{modal.rawContent}}}

 @ ./~/radon-ui/dist/components/global/modal.vue 7:23-139
 @ ./~/radon-ui/dist/components/index.js
 @ ./src/main.js
 @ multi main

**Comment by hilongjw** [comment]
@everpointer 感谢，目前比较缺乏vue2测试支持，我会马上修复这3个地方。

**Comment by everpointer** [comment]
非常感谢，还是希望尽快支持下vue 2.0，做到根据文档马上就能开始应用。
我也是刚学vue，所以就直接上vue 2.0了。正好想调研desktop UI，radon-ui 和 element-ui都是前后脚的时间。Element-ui 也没搭起来，貌似比较依赖cooking。
看了radon-ui 文档挺齐全，本来以为能够马上搞定的。。
期待修复，然后我再继续测试。

**Comment by hilongjw** [comment]
@everpointer 已在0.1.8 中修复了这个三个问题

**Comment by everpointer** [comment]
已测试，依然存在问题，问题如下：

**Comment by everpointer** [comment]
已测试，依然存在问题，问题如下：

progressCircle.vue: 49行
class 属性重复出现了

```
<path class="rc-progress-circle-path" d="M 50,50 m 0,-47
     a 47,47 0 1 1 0,94
     a 47,47 0 1 1 0,-94"
stroke-linecap="round" :stroke="color" 
class="path-style"
stroke-width="6" fill-opacity="0" 
style="stroke-dasharray: 295.31px, 295.31px; transition: stroke-dashoffset 0.6s ease 0s, stroke 0.6s ease;" :style="{ 'stroke-dashoffset': circle+'px' }">
</path>
```

#### 完整错误信息

RROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-28!./~/vue-loader/lib/selector.js?type=template&index=0!./~/radon-ui/dist/components/common/progressCircle.vue
template syntax error duplicate attribute: class
 @ ./~/radon-ui/dist/components/common/progressCircle.vue 7:23-148
 @ ./~/radon-ui/dist/components/index.js
 @ ./src/main.js
 @ multi main

**Comment by everpointer** [comment]
本地修复完上述错误后，有出现如下一些新的错误，应该都是vue 2.0 兼容性的问题，如下:
1. vue-animated-list，chrome console里报错 （可能不兼容vue2.0，貌似 vue 2.0 有 <transition-group> 可以用？）
2. modal, notification, loadingbar 和 preview 等都无法正常渲染，chrome console报错如下图:

![wechatimg2](https://cloud.githubusercontent.com/assets/1550412/18261802/8893270a-742e-11e6-944f-13706e04bc84.jpeg)

**Comment by everpointer** [comment]
上述具体错误还是先不贴了，感觉都是vue 2.0的问题。
有计划什么时候基于2.0重构，完全兼容2.0吗？
目前看来，用在vue 2.0上坑很多，先不踩了。

**Comment by LeslieYQ** [comment]
因为2.0 还没有正式发布，很多地方都可能改动，所以兼容上不是很好，后面会慢慢来修改的

**Comment by hilongjw** [comment]
@everpointer Vue 自带了过渡动画队列，所以也不需要 vue-animated-list，目前的全局组件在2.0中测试也有问题，在考虑解决方案。

**Comment by everpointer** [comment]
收到，期待完全兼容Vue 2.0的时刻，到时候继续体验

**Comment by QingWei-Li** [comment]
好巧居然看到有谈 Element UI 的... 现在已经剥离全局的 cooking 工具了，直接 clone 后 npm run dev 就可以跑起来。

**Comment by beeplin** [comment]
期待兼容vue2.0

**Comment by hilongjw** [comment]
已经在 [RadonUI 0.5.0](https://github.com/luojilab/radon-ui/tree/kyle) 支持Vue2.0
