### ISSUE TITLE
select选择器

### ISSUE THREAD

**Issue by treasureDouDou** [luojilab/radon-ui#25]
![image](https://cloud.githubusercontent.com/assets/21187862/18772358/bad642ae-8178-11e6-9d50-fd0adcaf94cf.png)

![image](https://cloud.githubusercontent.com/assets/21187862/18772366/d49bdd5c-8178-11e6-864e-a7c49fa66825.png)
点击展开后点击中间的会消失内容

**Comment by hilongjw** [comment]
@qq564526299  不是内容消失了，是开启了输入搜索状态，可以输入字符搜索过滤options，看来得加一个引导，或者把搜索移动到options list 的顶端。

**Comment by treasureDouDou** [comment]
@hilongjw 
![image](https://cloud.githubusercontent.com/assets/21187862/18776785/39cd492a-819e-11e6-9308-8e07b957688b.png)
输入的时候看不到的，有闪烁

**Comment by hilongjw** [comment]
@qq564526299 可以提供一下系统和浏览器版本

**Comment by treasureDouDou** [comment]
![image](https://cloud.githubusercontent.com/assets/21187862/18776858/a7a7a36e-819e-11e6-9c25-2e890e90d791.png)

**Comment by treasureDouDou** [comment]
w7 64

**Comment by hilongjw** [comment]
@qq564526299 已经将搜索功能改为了一个选项

```
selectProvince: {
                    search: true,
                    value: {},
                    options: []
                },
```
