### ISSUE TITLE
时间选择器能不能控制位置,如图

### ISSUE THREAD

**Issue by treasureDouDou** [luojilab/radon-ui#26]
![image](https://cloud.githubusercontent.com/assets/21187862/18781671/5e9c8fec-81b5-11e6-82d1-cd43cd5a7174.png)
能不能控制让他向下定位

**Comment by hilongjw** [comment]
@qq564526299 我会加上自动根据处于窗口的位置自动上或下展开

**Comment by hilongjw** [comment]
@qq564526299 datePicker 默认是根据所处屏幕上下位置自动布局的，针对这问题在 0.2.1 中添加了autoPosition 的配置项。

```
datePicker: {
                value: '',
                rawDate: {},
                options: {
                    autoPosition: false,
                    position: 'bottom' // 'top'
                }
            },
```
