### ISSUE TITLE
es5的项目无法使用么？

### ISSUE THREAD

**Issue by zhaoleis** [luojilab/radon-ui#28]
![image](https://cloud.githubusercontent.com/assets/10767337/19239162/5e5de348-8f37-11e6-8517-6862a815a668.png)
var RadonInstall = require('radon-ui')
Vue.use(RadonInstall);

**Comment by hilongjw** [comment]
@zhaoleis  需要使用 vue-loader 和 babel ，可以参考 https://github.com/luojilab/radon-ui-example
