### ISSUE TITLE
[发布准备]

### ISSUE THREAD

**Issue by hilongjw** [luojilab/radon-ui#3]
组件完成状态
- Basic
  - [x] Button 按钮
  - [x] ButtonGroup 按钮组
  - [x] DropButton 下拉
  - [x] Card 卡片 
  - [x] CardGroup 卡片组
  - [x] Icon 图标
  - [x] Table 表格
  - [x] Tag 标签
- Form
  - [x] Textfield 文本输入框
  - [x] NumberInput 数字输入框
  - [x] Checkbox 复选框
  - [x] Radio 单选框
  - [x] Switch 开关
  - [x] Slider 滑动输入
  - [x] Select 选择器
  - [x] Cascader 级联选择器
  - [x] Editable 可编辑文本
- Common
  - [x] Alert 警告提示
  - [x] Timeline 时间线
  - [x] Tooltip 对话框
  - [x] Spin 加载中
  - [x] Progress 进度条
  - [x] Upload 上传
  - [x] AudioPlayer 音频播放
- Global
  - [x] Modal 对话框
  - [x] Notification 通知
  - [x] Preview  图片预览
  - [x] LoadingBar 加载进度条
- Navigation
  - [x] Breadcrumb 面包屑
  - [x] Pagination 分页

文档状态
- Basic
  - [x] Button 按钮
  - [x] ButtonGroup 按钮组
  - [x] DropButton 下拉
  - [x] Card 卡片 
  - [x] CardGroup 卡片组
  - [x] Icon 图标
  - [x] Table 表格
  - [x] Tag 标签
- Form
  - [x] Textfield 文本输入框
  - [x] NumberInput 数字输入框
  - [x] Checkbox 复选框
  - [x] Radio 单选框
  - [x] Switch 开关
  - [x] Slider 滑动输入
  - [x] Select 选择器
  - [x] Cascader 级联选择器
  - [x] Editable 可编辑文本
- Common
  - [x] Alert 警告提示
  - [x] Timeline 时间线
  - [x] Tooltip 对话框
  - [x] Spin 加载中
  - [x] Progress 进度条
  - [x] Upload 上传
  - [x] AudioPlayer 音频播放
- Global
  - [x] Modal 对话框
  - [x] Notification 通知
  - [x] Preview  图片预览
  - [x] LoadingBar 加载进度条
- Navigation
  - [x] Breadcrumb 面包屑
  - [x] Pagination 分页

**Comment by xinshouke** [comment]
I am looking forward to it ...  When will it come?

**Comment by hilongjw** [comment]
@xinshouke thanks，it will be released within a few days

**Comment by ChaoYuLeo** [comment]
表格排序时，表头有箭头指示会更好

**Comment by myronliu347** [comment]
能多点动画就更好了，现在有些地方还比较生硬

**Comment by hilongjw** [comment]
@ChaoYuLeo 这个部分会分两个部分，前端排序和后端排序，之后会增加配置完善来。

**Comment by hilongjw** [comment]
@aa953788477 是的，之前是基础开发，现在会开始做设计和动效的优化

**Comment by cody1991** [comment]
也想尝试下组件开发用在公司里面，但是感觉有点无从下手。要做到像你这样的一个Vue组件库有什么指导或者资料吗，谢谢了

**Comment by taomas** [comment]
@cody1991 把他们的组件库抄一遍或者看着效果自己实现一遍！哈哈。

**Comment by cody1991** [comment]
@wendaosanshou ...我确实打算开始这样做...

**Comment by hilongjw** [comment]
@cody1991 这个方面现成的资料可能不好找，但是你可以在github上找到一些不错的组件库来参考，比如参考一些优秀的React 组件的实现，可以结合 Vue 的特性来封装改写。

**Comment by cody1991** [comment]
@hilongjw 好的，谢谢~
