### ISSUE TITLE
Preview 图片预览问题

### ISSUE THREAD

**Issue by codown-d** [luojilab/radon-ui#30]
第一张图片显示没有居中  再次退回显示就居中了 （如果看不见现象 刷新页面再打开应该就会有了）
https://luojilab.github.io/radon-ui/#!/global/preview

**Comment by hilongjw** [comment]
@codeMarker213 目前是有这个问题，我们正在准备优化这个组件图片加载loading 和 修复第一张图片的布局问题。

**Comment by hilongjw** [comment]
@codeMarker213 已经在 0.2.5 版本中优化了 preview
