### ISSUE TITLE
radon-ui是否能够兼容支持vuejs2.0呢？

### ISSUE THREAD

**Issue by cnweibo** [luojilab/radon-ui#32]
vuejs2.0推出后和1.0有很多不兼容的地方，特别是.sync, eventbus, broadcast/dispatch以及directive的写法都有很多变化，是否能够将这个库整成兼容vuejs2.0?

**Comment by hilongjw** [comment]
@cnweibo  我们在开发中尽量避免使用.sync broadcast 等在2.0中被废弃的特性，升级成本不是很高，已有计划升级支持2.0。

**Comment by hilongjw** [comment]
@cnweibo RadonUI 0.5.0已经支持 Vue2.0
