### ISSUE TITLE
loadingbar组件报错

### ISSUE THREAD

**Issue by deboyblog** [luojilab/radon-ui#33]
vue.common.js?c653:1137[Vue warn]: Error when evaluating expression "{
  'width': loadingBar.percent+'%',
  'height': loadingBar.options.height,
  'background-color': loadingBar.options.canSuccess? loadingBar.options.color : loadingBar.options.failedColor,
  'opacity': loadingBar.options.show ? 1 : 0
}": TypeError: Cannot read property 'percent' of undefined (found in component: <rd-loadingbar>)
![sp20161022_170451](https://cloud.githubusercontent.com/assets/11410323/19618324/aea2ba86-9879-11e6-99f7-80bb01c016ed.png)
按照官方文档来用的 全局引入了

**Comment by hilongjw** [comment]
@deboyblog 可以提供一下现在使用的版本和相关代码吗？

**Comment by deboyblog** [comment]
vue: 1.0.28
radon-ui: 0.2.5
已经换其他解决方案了 代码已经删除了
