### ISSUE TITLE
树组件bug

### ISSUE THREAD

**Issue by keepnode** [luojilab/radon-ui#36]
首先，感谢您这么快就加进来了~~~
发现一个bug.
目前演示的例子是3级菜单，但是如果2级选中的情况下，再一级菜单中勾选，应该是全部选择，而现在是之前选中的2级菜单和3级菜单，则出现反选情况。。
![image](https://cloud.githubusercontent.com/assets/8043218/20591835/82a8094e-b265-11e6-8337-b1e171bd34c7.png)

![image](https://cloud.githubusercontent.com/assets/8043218/20591819/73a14c26-b265-11e6-901c-aaf566a31d1f.png)

**Comment by LeslieYQ** [comment]
恩， 我们也发现了，会修改一个。

**Comment by LeslieYQ** [comment]
改好了
