### ISSUE TITLE
还会增加其他的组件吗？

### ISSUE THREAD

**Issue by PassionZale** [luojilab/radon-ui#37]
例如轮播图等，还有菜单导航，导航好像一个都没有哦

**Comment by LeslieYQ** [comment]
会， 有需要就会，你也可以给我们提需求。 现在有一个面包屑导航

**Comment by PassionZale** [comment]
想提一个轮播图，虽然现在也有很多单独的轮播vue组件，不过感觉用radon-ui，就想用ui本身的，哈哈。

**Comment by PassionZale** [comment]
最近公司在做微信商城，用的饿了么的那套UI，我觉得radon-ui样式很不错，文档也很易懂，组件齐全的话，准备替换掉饿了么那套UI了。

**Comment by LeslieYQ** [comment]
好的，轮播图加上。 我们的移动端兼容不是特别好，你要注意一下。

**Comment by PassionZale** [comment]
1.  每张banner需要显示title，v-show控制，title为空就不显示title的样式
2. 默认跳转连接是空，跳转方式绑定v-href=""，或者直接写跳转url，如http://www.xxx.xx
这是现在我实际开发中的需求，后台在录入banner的时候，需要填写banner标题，和跳转连接。

**Comment by PassionZale** [comment]
等把radon-ui用熟了，我也想贡献一些组件出来，希望到时候可以加入你们的开发！

**Comment by hilongjw** [comment]
@PassionZale  计划把 [https://github.com/hilongjw/vue-slide](https://github.com/hilongjw/vue-slide) 整合进 radon

**Comment by hilongjw** [comment]
@PassionZale 已经加入 [swipe 组件 ](https://luojilab.github.io/radon-ui/0.5.0/#/basic/swipe)

**Comment by PassionZale** [comment]
@hilongjw 好的！
