### ISSUE TITLE
按照安装手册的引入css报错，到底要如何引入

### ISSUE THREAD

**Issue by SimpleSimple** [luojilab/radon-ui#39]
这是目录结构
![image](https://cloud.githubusercontent.com/assets/8638934/21219051/10b2d028-c2ee-11e6-9557-aef2225f8142.png)

在App.vue这样引用css
<style src="radon-ui/dist/radon-ui.css"></style>

报错信息：
ERROR in ./~/radon-ui/dist/static/fonts/ionicons.eot
Module parse failed: F:\WANG\www\vue2\vue-test\node_modules\radon-ui\dist\static
\fonts\ionicons.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-b36d6
4fc!./~/radon-ui/dist/radon-ui.css 6:7948-7986 6:8004-8042
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewrit
er.js?id=data-v-b36d64fc!./~/radon-ui/dist/radon-ui.css
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main

[
![image](https://cloud.githubusercontent.com/assets/8638934/21219181/a2e0c086-c2ee-11e6-8ba7-b2f0e2260536.png)
](url)

**Comment by hilongjw** [comment]
@SimpleSimple 在 RadonUI 0.5.0版本对路径进行了一点修改

```html
0.5.0 之后
<style src="radon-ui/dist/radon-ui.css"></style>

0.5.0 之前
<style src="radon-ui/dist/static/css/dist.css"></style>
```

**Comment by SimpleSimple** [comment]
@hilongjw 问下是这样在App.vue文件里引用css文件吗
[
![image](https://cloud.githubusercontent.com/assets/8638934/21248532/a3acac08-c372-11e6-944d-bebd516a7cd7.png)
](url)
我还是会报上面那样的错
看了下版本，应该是0.5.1的
` "_from": "radon-ui@latest",
  "_id": "radon-ui@0.5.1",
  "_inCache": true,
  "_installable": true,
  "_location": "/radon-ui",
  "_nodeVersion": "6.2.1",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/radon-ui-0.5.1.tgz_1481283769518_0.816650545457378"
  },`

**Comment by hilongjw** [comment]
@SimpleSimple 是的，在根实例 App.vue 中引入就可以了, 建议可以升级到 0.5.2 在这个版本中优化了 css ，减少了文件大小。
```html
<style src="radon-ui/dist/radon-ui.css"></style>
```

**Comment by hilongjw** [comment]
@SimpleSimple  还有一个问题是，你需要在webpack配置中配置 字体文件的加载器

```javascript
, {
            test: /\.(svg|ttf|woff|eot)$/,
            loader: 'file-loader',
            query: {
                name: 'file/[name].[ext]'
            }
        }
```
